services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: nexus_admin
      POSTGRES_PASSWORD: nexus_password
      POSTGRES_DB: nexushub
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data: