/**
 * @file layout.tsx  (app/layout.tsx)
 * @description Root layout for the NexusHub Next.js application.
 *
 * This file is the single shared layout wrapping every page in the app router.
 * It is rendered on the server and provides:
 *  - Font variables (Geist Sans + Geist Mono) injected as CSS custom properties
 *    so they are available globally via Tailwind's font-sans / font-mono utilities.
 *  - The `<html>` and `<body>` shell required for the document.
 *  - Global CSS import (Tailwind base + component layers).
 *  - SEO metadata exported via Next.js `Metadata` API (title, description).
 *
 * To update site-wide metadata, modify the `metadata` export.
 * Per-page metadata can be exported from any page.tsx inside the app directory.
 */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Load Geist Sans and inject it as a CSS variable used by Tailwind's font-sans
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Load Geist Mono and inject it as a CSS variable used by Tailwind's font-mono
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Site-wide default metadata — overridden per-page when needed
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout
 *
 * Wraps every page in the application. `children` receives the rendered
 * output of the matched page segment (and any nested layouts).
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
