/**
 * @file prisma.config.ts
 * @description Prisma CLI configuration file (for the `prisma` CLI tool).
 *
 * This file was generated by Prisma, and assumes you have installed the following:
 * npm install --save-dev prisma dotenv
 *
 * Purpose:
 *  Configures the Prisma CLI (used for `migrate`, `generate`, `studio`, etc.)
 *  with the schema path, migrations directory, and database URL.
 *
 * Note — `import "dotenv/config"`:
 *  The Prisma CLI does NOT automatically read `.env` files.
 *  This import loads the .env file before `defineConfig` reads `env('DATABASE_URL')`,
 *  ensuring the CLI has access to the correct connection string during migrations.
 *
 * This file is only used by the Prisma CLI — at runtime, the application
 * reads DATABASE_URL directly via `config/env.ts` using dotenv.
 */

// Load .env file into process.env so the CLI can access DATABASE_URL
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  // Path to the Prisma schema file (relative to this config file)
  schema: "prisma/schema.prisma",

  migrations: {
    // Directory where migration SQL files are stored
    path: "prisma/migrations",
  },

  datasource: {
    // Reads DATABASE_URL from the loaded .env file
    url: env('DATABASE_URL'),
  },
});